"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { buildConversationClues } from "@/lib/conversation-clues";

type Tier = "white" | "blue" | "purple" | "orange" | "gold";
type PortraitStyle = "cartoon" | "realistic";
type PortraitVariant = { assetPath?:string;alt:string;representation:"historical_portrait"|"evidence_based_reconstruction"|"artistic_interpretation";sourceLabel?:string;license?:string };
type CharacterExhibit = { overview:string;biography:string[];influence:string;legacy:string;works:string[];conversationStarters:string[];discoveries:Array<{id:string;kind:string;title:string;content:string;keywords:string[]}> };
type Character = { id:string;periodId:string;name:string;initial:string;life:string;tier:Tier;curatorRole:string;summary:string;exhibit:CharacterExhibit;relationCharacterIds:string[];portraitVariants:{cartoon:PortraitVariant;realistic:PortraitVariant} };
type Hall = { id:string;title:string;question:string;characterIds:string[] };
type Period = { id:string;title:string;years:string;place:string;mark:string;theme:"tang"|"renaissance"|"physics";inquiry:string;halls:Hall[];characters:Character[] };
type Collection = { ownedCharacterIds:string[];stars:number;fragments:number;firstFreeEligible:boolean;firstFreeUsed:boolean;revision:number };
type Draw = { id:string;periodId:string;resultCharacterId:string;duplicate:boolean;fragmentReward:number;costStars:number;status:"committed"|"revealed" };
type ExploreData = { periods:Period[];collection:Collection;pendingDraw:Draw|null };
type Thread = { id:string;characterId:string;summary?:string;lastMessageAt?:string };
type Message = { id?:string;role:"user"|"character";content:string;citations?:Array<{sourceId:string;title:string;locator:string}>;characterVersion?:string;narrator?:string };
type Route = "home"|"explore"|"period"|"hall"|"encounter"|"person"|"museum"|"pack"|"chat";
type ChatFontSize = "small"|"medium"|"large";

const routeNames:Record<Route,string>={home:"主页",explore:"探索历史",period:"历史时期",hall:"历史展厅",encounter:"人物相遇",person:"人物资料",museum:"我的博物馆",pack:"人物卡包",chat:"长期对话"};
const tierLabels:Record<Tier,string>={white:"线索人物",blue:"关键人物",purple:"核心人物",orange:"时代人物",gold:"典藏人物"};
const validRoutes=new Set(Object.keys(routeNames));
const initialOwnedCount=36;

function uuid(){return globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random()}`}

export function Museum(){
  const [dataState,setData]=useState<ExploreData|null>(null);
  const data:ExploreData=dataState??{periods:[],collection:{ownedCharacterIds:[],stars:0,fragments:0,firstFreeEligible:false,firstFreeUsed:false,revision:0},pendingDraw:null};
  const [route,setRoute]=useState<Route>("home");
  const [mode,setMode]=useState<"child"|"adult">("child");
  const [periodId,setPeriodId]=useState("physics-revolution");
  const [selectedId,setSelectedId]=useState("albert-einstein");
  const [hallId,setHallId]=useState("physics-solvay");
  const [expanded,setExpanded]=useState(false);
  const [searchOpen,setSearchOpen]=useState(false);
  const [settingsOpen,setSettingsOpen]=useState(false);
  const [search,setSearch]=useState("");
  const [evidenceSeen,setEvidenceSeen]=useState(false);
  const [encounterDone,setEncounterDone]=useState(false);
  const [drawResult,setDrawResult]=useState<Draw|null>(null);
  const [confirmDraw,setConfirmDraw]=useState(false);
  const [notice,setNotice]=useState("");
  const [error,setError]=useState("");
  const [loading,setLoading]=useState(true);
  const [threads,setThreads]=useState<Thread[]>([]);
  const [threadId,setThreadId]=useState("");
  const [messages,setMessages]=useState<Message[]>([]);
  const [input,setInput]=useState("");
  const [busy,setBusy]=useState(false);
  const [runtimeMode,setRuntimeMode]=useState("正在检测模型能力");
  const [portraitStyles,setPortraitStyles]=useState<Record<string,PortraitStyle>>({});
  const [chatFontSize,setChatFontSize]=useState<ChatFontSize>("medium");
  const [memoOpen,setMemoOpen]=useState(false);
  const chatScrollRef=useRef<HTMLDivElement>(null);
  const latestMessageRef=useRef<HTMLDivElement>(null);
  const chatInputRef=useRef<HTMLInputElement>(null);

  const refreshExplore=useCallback(async()=>{
    const response=await fetch("/api/explore"); if(!response.ok)throw new Error("无法加载历史目录");
    const next=await response.json() as ExploreData; setData(next); return next;
  },[]);
  const refreshThreads=useCallback(async()=>{const response=await fetch("/api/threads");const next=await response.json();setThreads(next.threads??[]);return next.threads??[] as Thread[]},[]);

  useEffect(()=>{void(async()=>{try{
    const saved=localStorage.getItem("ai-museum-visitor");if(saved){const state=JSON.parse(saved);if(state.mode)setMode(state.mode);if(state.periodId)setPeriodId(state.periodId);if(state.selectedId)setSelectedId(state.selectedId);if(state.hallId)setHallId(state.hallId);if(state.portraitStyles)setPortraitStyles(state.portraitStyles);if(["small","medium","large"].includes(state.chatFontSize))setChatFontSize(state.chatFontSize)}
    const queryMode=new URLSearchParams(location.search).get("mode");if(queryMode==="child"||queryMode==="adult")setMode(queryMode);
    const hash=location.hash.slice(1);if(validRoutes.has(hash))setRoute(hash as Route);
    await refreshExplore();await refreshThreads();
  }catch(reason){setError(reason instanceof Error?reason.message:"页面加载失败")}finally{setLoading(false)}})()},[refreshExplore,refreshThreads]);
  useEffect(()=>{const onHash=()=>{const hash=location.hash.slice(1);if(validRoutes.has(hash))setRoute(hash as Route)};addEventListener("hashchange",onHash);return()=>removeEventListener("hashchange",onHash)},[]);
  useEffect(()=>{try{localStorage.setItem("ai-museum-visitor",JSON.stringify({mode,periodId,selectedId,hallId,portraitStyles,chatFontSize}))}catch{}},[mode,periodId,selectedId,hallId,portraitStyles,chatFontSize]);

  const periods=data?.periods??[];
  const period=periods.find(item=>item.id===periodId)??periods[0];
  const characters=periods.flatMap(item=>item.characters);
  const selected=characters.find(item=>item.id===selectedId)??characters[0];
  const hall=period?.halls.find(item=>item.id===hallId)??period?.halls[0];
  const selectedHall=period?.halls.find(item=>item.characterIds.includes(selected?.id))??hall;
  const owned=(id:string)=>Boolean(data?.collection.ownedCharacterIds.includes(id));
  const ownedInPeriod=(p:Period)=>p.characters.filter(character=>owned(character.id)).length;

  function go(next:Route){setRoute(next);setError("");setNotice("");if(location.hash!==`#${next}`)location.hash=next;scrollTo({top:0,behavior:"smooth"})}
  function choosePeriod(next:Period,target:Route="period"){setPeriodId(next.id);setHallId(next.halls[0].id);setExpanded(false);go(target)}
  function choosePerson(character:Character,target:Route="person"){setSelectedId(character.id);setPeriodId(character.periodId);setEvidenceSeen(false);setEncounterDone(false);setMemoOpen(false);setSearchOpen(false);go(target)}
  function setVisualMode(next:"child"|"adult"){
    setMode(next);
    const url=new URL(location.href);url.searchParams.set("mode",next);history.replaceState(null,"",`${url.pathname}${url.search}${url.hash}`);
    toast(next==="child"?"已切换到轻快版":"已切换到典藏版");
  }
  function portraitStyle(character:Character){return portraitStyles[character.id]??(mode==="child"?"cartoon":"realistic")}
  function togglePortrait(character:Character){setPortraitStyles(current=>({...current,[character.id]:portraitStyle(character)==="cartoon"?"realistic":"cartoon"}))}
  function toast(message:string){setNotice(message);setTimeout(()=>setNotice(current=>current===message?"":current),2600)}
  function beginWithQuestion(question:string){setInput(question);go("chat");setTimeout(()=>chatInputRef.current?.focus(),80)}

  const openThread=useCallback(async(characterId:string)=>{
    const createdResponse=await fetch("/api/threads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({characterId})});
    const created=await createdResponse.json();if(!created.thread)throw new Error(created.error??"无法打开对话");
    setThreadId(created.thread.id);const historyResponse=await fetch(`/api/threads/${created.thread.id}/messages`);const history=await historyResponse.json();setMessages(history.messages??[]);await refreshThreads();
  },[refreshThreads]);
  useEffect(()=>{if(route!=="chat"||!selected||!owned(selected.id))return;void openThread(selected.id).catch(reason=>setError(reason instanceof Error?reason.message:"无法恢复对话"))},[route,selected?.id,openThread]);
  useEffect(()=>{if(route!=="chat"||messages.length===0)return;const frame=requestAnimationFrame(()=>{const container=chatScrollRef.current;const target=latestMessageRef.current;if(!container||!target)return;const top=container.scrollTop+target.getBoundingClientRect().top-container.getBoundingClientRect().top-10;container.scrollTo({top:Math.max(0,top),behavior:"smooth"})});return()=>cancelAnimationFrame(frame)},[route,threadId,messages]);

  async function completeEncounter(){if(!selected||!period||encounterDone)return;setBusy(true);setError("");try{
    const response=await fetch("/api/exploration-events",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({characterId:selected.id,periodId:period.id,type:"encounter_completed",idempotencyKey:`encounter:${selected.id}`})});
    const result=await response.json();if(!response.ok)throw new Error(result.error??"相遇没有保存");
    setData(current=>current?{...current,collection:result.collection}:current);setEncounterDone(true);toast(result.repeated?"这次相遇之前已经记录过":"完成相遇：获得20探索星和首次免费开包");setTimeout(()=>go("pack"),650);
  }catch(reason){setError(reason instanceof Error?reason.message:"相遇没有保存")}finally{setBusy(false)}}

  async function draw(){if(!period||busy)return;setBusy(true);setError("");try{
    const idempotencyKey=uuid();const response=await fetch("/api/draws",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({periodId:period.id,idempotencyKey})});
    const result=await response.json();if(!response.ok)throw new Error(result.error??"人物卡开启失败");
    setData(current=>current?{...current,collection:result.collection,pendingDraw:result.draw}:current);setDrawResult(result.draw);setConfirmDraw(false);
  }catch(reason){setConfirmDraw(false);setError(reason instanceof Error?reason.message:"人物卡开启失败")}finally{setBusy(false)}}
  async function acknowledgeDraw(target:Route){if(!drawResult)return;try{await fetch(`/api/draws/${drawResult.id}/reveal`,{method:"POST"})}catch{}const resultCharacter=characters.find(item=>item.id===drawResult.resultCharacterId);if(resultCharacter)setSelectedId(resultCharacter.id);setDrawResult(null);setData(current=>current?{...current,pendingDraw:null}:current);go(target)}

  async function ask(){const question=input.trim();if(!question||busy||!threadId)return;setInput("");setBusy(true);setError("");const optimistic:Message={role:"user",content:question};setMessages(current=>[...current,optimistic]);try{
    const response=await fetch(`/api/threads/${threadId}/messages`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:question,ageBand:"9-12",locale:"zh-CN"})});const result=await response.json();if(!response.ok)throw new Error(result.error??"回答失败");
    setMessages(current=>[...current,{id:result.messageId,role:"character",content:result.answer,citations:result.citations,characterVersion:result.version,narrator:result.narratorNote}]);
    const evidence=Array.isArray(result.citations)&&result.citations.length>0;
    setRuntimeMode(result.mode==="cloud-model"?(result.boundary?"云模型已连接 · 人物边界":evidence?"云模型 · 馆藏史料增强":"云模型 · 角色演绎"):result.mode==="local-model"?(evidence?"本地模型 · 馆藏史料增强":"本地模型 · 角色演绎"):"规则模式 · 未配置模型 Key");await refreshThreads();
  }catch(reason){setMessages(current=>current.slice(0,-1));setInput(question);setError(reason instanceof Error?reason.message:"回答失败")}finally{setBusy(false);requestAnimationFrame(()=>chatInputRef.current?.focus())}}

  const searchResults=useMemo(()=>{const query=search.trim();if(!query)return[];const direct=characters.filter(character=>character.name.toLowerCase().includes(query.toLowerCase()));const relationIds=new Set(direct.flatMap(character=>character.relationCharacterIds));const related=characters.filter(character=>relationIds.has(character.id)&&!direct.some(item=>item.id===character.id));return[...direct.map(character=>({character,reason:"姓名匹配"})),...related.map(character=>({character,reason:`与${direct[0]?.name??"搜索人物"}有正式关系线索`}))].slice(0,8)},[search,characters]);
  const conversationClues=useMemo(()=>selected?buildConversationClues(selected,messages):[],[selected,messages]);

  if(loading)return <main className={`visitor-app ${mode}`}><div className="visitor-loading"><span>AI MUSEUM</span><h1>正在打开历史大门…</h1></div></main>;
  if(!dataState||!period||!selected)return <main className="visitor-app child"><div className="visitor-loading"><h1>历史目录没有准备好</h1><p>{error}</p><button type="button" className="primary" onClick={()=>location.reload()}>重新加载</button></div></main>;

  function portraitFace(character:Character,style:PortraitStyle){const variant=character.portraitVariants?.[style];return <span className={`portrait-face portrait-${style}`} aria-hidden="true"><span className="portrait-art">{variant?.assetPath?<img src={variant.assetPath} alt=""/>:<span className="portrait-placeholder"><b>{character.initial}</b><small>{style==="cartoon"?"卡通形象待添加":"写实形象待添加"}</small></span>}</span><span className="portrait-provenance">{variant?.sourceLabel??"形象来源待补充"}</span></span>}
  function portrait(character:Character,size:"mini"|"large"|"stage"="mini"){const style=portraitStyle(character);const current=style==="cartoon"?"卡通":"写实";const next=style==="cartoon"?"写实":"卡通";return <button type="button" className={`portrait-button portrait-${size}`} data-style={style} onClick={event=>{event.stopPropagation();togglePortrait(character)}} aria-label={`当前为${current}形象，切换为${next}形象`} title={`当前为${current}形象，点击切换`}><span className="portrait-card-inner">{portraitFace(character,"cartoon")}{portraitFace(character,"realistic")}</span><span className="portrait-switch-hint" aria-hidden="true">↻ {current}</span></button>}
  function messageAvatar(character:Character){const preferred=character.portraitVariants[portraitStyle(character)];const source=preferred.assetPath??character.portraitVariants.realistic.assetPath;return <span className="message-avatar character-avatar" aria-hidden="true">{source?<img src={source} alt=""/>:character.initial}</span>}

  function header(){return <header className="visitor-header"><a className="visitor-brand" href="/" aria-label="返回 AI Museum 入口页">AI Museum</a><nav aria-label="主要导航"><button className={route==="home"?"active":""} onClick={()=>go("home")}>主页</button><button className={["explore","period","hall","encounter","person"].includes(route)?"active":""} onClick={()=>go("explore")}>探索历史</button><button className={["museum","pack","chat"].includes(route)?"active":""} onClick={()=>go("museum")}>我的博物馆</button></nav><button className="visitor-search-trigger" onClick={()=>setSearchOpen(true)} aria-label="搜索人物或关系">⌕ <span>搜索人物或关系</span></button><button className="star-pill" onClick={()=>toast("探索星只来自真实学习事件")}>✦ {data.collection.stars}</button><button className="mode-toggle" onClick={()=>setSettingsOpen(true)} aria-label="打开入口与显示设置">入口与显示</button></header>}

  function periodCard(item:Period){return <button key={item.id} className={`period-card ${item.theme}`} data-mark={item.mark} onClick={()=>choosePeriod(item)}><span>{item.years} · 已认识 {ownedInPeriod(item)}/12</span><h2>{item.title}</h2><p>{item.inquiry}</p><b>进入这个时期 →</b>{mode==="adult"&&<small>{item.place}</small>}</button>}
  function personCard(character:Character,reason?:string,interactive=true){const details=<><b>{character.name}</b><small>{reason??`${character.life} · ${tierLabels[character.tier]}`}</small><em className={owned(character.id)?"owned":"public"}>{owned(character.id)?"✓ 已获得 · 可长期对话":"生平开放 · 长期对话待解锁"}</em></>;return <article key={character.id} className={`person-card tier-${character.tier}`}>{portrait(character,"mini")}{interactive?<button type="button" className="person-card-main" onClick={()=>choosePerson(character)} aria-label={`打开${character.name}的人物资料`}>{details}</button>:<div className="person-card-main">{details}</div>}</article>}

  function home(){const recent=threads[0];const recentCharacter=recent?characters.find(item=>item.id===recent.characterId):undefined;return <><section className="visitor-hero"><p>好用 · 好玩 · 有教育意义</p><h1>{recentCharacter?"继续你的历史旅程":"今天想进入哪一段历史？"}</h1><span>{recentCharacter?"你与每位人物的旧对话都会独立保存。":"先走进历史场景，再与人物建立长期关系。"}</span></section>{recentCharacter?<article className="continue-card">{portrait(recentCharacter,"large")}<div><small>继续上次对话</small><h2>{recentCharacter.name}</h2><p>{recent?.summary??recentCharacter.summary}</p><div className="actions"><button className="primary" onClick={()=>choosePerson(recentCharacter,"chat")}>继续长期对话</button><button className="secondary" onClick={()=>choosePerson(recentCharacter,"person")}>看看人物资料</button></div></div></article>:<article className="first-step"><div><small>第一次探索</small><h2>选择一个历史时期，从推荐展厅开始</h2><p>完成一次有史料依据的人物相遇后，将获得20探索星和一次免费开包。</p></div><button className="primary" onClick={()=>go("explore")}>选择历史时期</button></article>}<div className="center-actions"><button className="secondary" onClick={()=>go("museum")}>打开我的博物馆 · {data.collection.ownedCharacterIds.length}/{initialOwnedCount}</button></div></>}
  function explore(){return <><section className="visitor-hero"><p>第一步 · 选择历史时期</p><h1>你想走进哪一段历史？</h1><span>每个时期有12位人物和3个由时间、地点与关系组织的展厅。</span></section><div className="period-grid">{periods.map(periodCard)}</div></>}
  function periodView(){const visible=expanded?period.characters:period.characters.slice(0,3);return <><section className={`period-hero ${period.theme}`} data-mark={period.mark}><small>{period.years} · {period.place}</small><h1>{period.title}</h1><p>{period.inquiry}</p><div className="actions"><button className="primary" onClick={()=>go("hall")}>进入推荐展厅</button><button className="secondary" onClick={()=>go("pack")}>查看本时期卡包</button></div></section><section className="section-title"><div><small>从一个真实场景开始</small><h2>三个历史展厅</h2></div><span>人物因共同事件和证据相连</span></section><div className="hall-grid">{period.halls.map((item,index)=><article className="hall-card" key={item.id}><small>展厅 {index+1}</small><h3>{item.title}</h3><p>{item.question}</p><button className={index===0?"primary":"secondary"} onClick={()=>{setHallId(item.id);go("hall")}}>{index===0?"进入推荐展厅":"看看这个展厅"}</button></article>)}</div><section className="section-title"><div><small>{expanded?"本时期完整名册":"推荐起始人物"}</small><h2>{expanded?"12位人物":"先认识这3位"}</h2></div><button className="secondary" onClick={()=>setExpanded(value=>!value)}>{expanded?"收起名册":"查看全部12人"}</button></section><div className="people-grid">{visible.map(character=>personCard(character))}</div></>}
  function hallView(){const people=(hall?.characterIds??[]).map(id=>characters.find(item=>item.id===id)).filter(Boolean) as Character[];const starter=people.find(item=>!owned(item.id))??people[0]??period.characters[0];return <><section className="visitor-hero"><p>{period.years} · {period.place}</p><h1>{hall?.title}</h1><span>{hall?.question}</span></section><div className="hall-grid"><article className="hall-card"><small>发生了什么</small><h3>从时间、地点和一条史料开始</h3><p>博物馆旁白会说明人物亲历、当时可知和后人评价的区别。</p></article><article className="hall-card featured"><small>推荐人物</small><h3>{starter.name}</h3><p>{starter.summary}。完成引导式相遇不要求先获得人物卡。</p><button className="primary" onClick={()=>choosePerson(starter,"encounter")}>和{starter.name}相遇</button></article><article className="hall-card"><small>学习奖励</small><h3>史料依据 + 有效追问</h3><p>首次完成后获得20探索星，并开放一次免费人物卡。</p></article></div><section className="section-title"><h2>这个展厅里的人</h2><button className="secondary" onClick={()=>go("period")}>返回时期馆</button></section><div className="people-grid">{people.map(character=>personCard(character))}</div></>}
  function encounter(){const relations=selected.relationCharacterIds.map(id=>characters.find(item=>item.id===id)).filter(Boolean).slice(0,2) as Character[];return <section className="encounter-shell"><header className="encounter-nav"><div><small>博物馆相遇 · 不要求已获得</small><b>{selectedHall?.title}</b></div><button className="secondary" onClick={()=>go("hall")}>返回展厅</button></header><div className="meeting-room"><article className="presence-stage">{portrait(selected,"stage")}<div><small>{selected.curatorRole}</small><h1>{selected.name}</h1><p>{selected.life} · {period.title}</p><span>点击形象可在卡通版与写实版之间切换</span></div></article><article className="presence-intro"><small>30秒认识我</small><h2>{selected.summary}</h2><p><b>为什么在这里：</b>{selectedHall?.title}把我与同一事件、地点或知识网络中的人物连接起来。</p><div className="time-place"><span>时间 · {selected.life}</span><span>地点 · {period.place}</span></div>{relations.length>0&&<div className="relation-links"><b>可以顺着关系认识</b>{relations.map(relation=><button className="quiet" key={relation.id} onClick={()=>choosePerson(relation,"person")}>{relation.name}</button>)}</div>}<div className="prompt-chips" aria-label="推荐问题"><span>当时发生了什么？</span><span>你为什么这样选择？</span><span>谁影响了你？</span></div></article></div><div className="conversation-stage"><article className="bubble character">欢迎来到这段历史。你可以先从一个选择、一段关系或一件当时发生的事问起。</article><article className="bubble user">你为什么会出现在这个历史展厅？</article><article className="bubble character">{selected.summary}。正式回答会受人物认知边界约束，历史断言必须绑定已审核 Claim。{evidenceSeen&&<aside className="source-card"><b>史料依据</b><span>本地样例人物包 · 来源定位和许可会在正式 Claim 旁展示。人物第一人称与博物馆旁白严格分开。</span></aside>}</article><div className="actions"><button className="secondary" onClick={()=>setEvidenceSeen(true)}>{evidenceSeen?"✓ 已查看依据":"看看依据"}</button>{evidenceSeen&&!encounterDone&&<button className="primary" disabled={busy} onClick={()=>void completeEncounter()}>{busy?"正在保存…":"完成相遇 · +20探索星"}</button>}</div></div><div className="sample-composer"><input disabled placeholder="引导相遇中的自由提问将在模型接入后开放"/><button disabled>发送</button></div></section>}
  function personView(){const relations=selected.relationCharacterIds.map(id=>characters.find(item=>item.id===id)).filter(Boolean) as Character[];return <div className="profile-layout rich-profile"><aside className="profile-side">{portrait(selected,"large")}<h1>{selected.name}</h1><p>{selected.life} · {tierLabels[selected.tier]}</p><em className={owned(selected.id)?"owned":"public"}>{owned(selected.id)?"✓ 已获得":"基本资料开放"}</em><div className="actions">{owned(selected.id)?<button className="primary" onClick={()=>go("chat")}>继续长期对话</button>:<button className="primary" onClick={()=>go("encounter")}>完成博物馆相遇</button>}<button className="secondary" onClick={()=>go("hall")}>查看相关历史</button></div><div className="profile-period"><small>所在时空</small><b>{period.title}</b><span>{period.years} · {period.place}</span></div></aside><section className="profile-main"><small>公开人物资料</small><h2>{selected.exhibit.overview}</h2><p className="profile-lead">先了解这个人的经历与处境，再选择一个真正想问的问题。</p><section className="profile-section"><h3>一生中的几个转折</h3><ol className="life-timeline">{selected.exhibit.biography.map((item,index)=><li key={item}><span>{index+1}</span><p>{item}</p></li>)}</ol></section><div className="profile-story-grid"><article><small>如何影响时代</small><h3>他改变了什么</h3><p>{selected.exhibit.influence}</p></article><article><small>后人的眼光</small><h3>为什么今天仍在谈论</h3><p>{selected.exhibit.legacy}</p></article></div><section className="profile-section"><h3>作品、事件与思想</h3><div className="work-chips">{selected.exhibit.works.map(work=><span key={work}>{work}</span>)}</div></section><section className="profile-section"><h3>与他相连的人</h3><div className="profile-relations">{relations.length?relations.slice(0,5).map(relation=><button className="secondary" key={relation.id} onClick={()=>choosePerson(relation,"person")}>{relation.name}</button>):<span>关系资料正在整理</span>}</div></section><section className="profile-section conversation-starters"><small>不知道从哪里聊起？</small><h3>带着一个好问题去见他</h3><div>{selected.exhibit.conversationStarters.map(question=><button className="secondary" key={question} onClick={()=>beginWithQuestion(question)}>{question}</button>)}</div></section></section></div>}
  function museum(){const ownedCharacters=characters.filter(character=>owned(character.id));const pending=data.pendingDraw;const pendingCharacter=pending?characters.find(item=>item.id===pending.resultCharacterId):undefined;return <><section className="visitor-hero"><p>我的博物馆</p><h1>已认识 {data.collection.ownedCharacterIds.length} / 36 位人物</h1><span>人物卡解锁长期关系；公共历史知识始终开放。</span></section>{pending&&pendingCharacter&&<article className="first-step pending"><div><small>最近获得 · 结果已经保存</small><h2>{pendingCharacter.name}正在等待你</h2><p>即使关闭或刷新，这位人物仍已加入博物馆。</p></div><button className="primary" onClick={()=>{setDrawResult(pending)}}>查看结果</button></article>}<div className="museum-overview"><article><h2>{data.collection.ownedCharacterIds.length}/36</h2><div className="progress"><i style={{width:`${data.collection.ownedCharacterIds.length/36*100}%`}}/></div><p>探索星 {data.collection.stars} · 史料碎片 {data.collection.fragments}</p><button className="primary" onClick={()=>go("explore")}>继续探索历史</button></article><article>{periods.map(item=><div className="collection-row" key={item.id}><span>{item.title}</span><b>{ownedInPeriod(item)}/12</b><button className="secondary" onClick={()=>choosePeriod(item,"pack")}>卡包</button></div>)}</article></div><section className="section-title"><h2>已获得人物</h2><span>点击打开人物资料</span></section><div className="people-grid">{ownedCharacters.map(character=>personCard(character))}</div></>}
  function pack(){const free=data.collection.firstFreeEligible&&!data.collection.firstFreeUsed;const complete=ownedInPeriod(period)===12;return <><div className="pack-layout"><article className={`pack-cover ${period.theme}`}><small>{period.years} · 12位首发人物</small><h1>{period.title}</h1><p>{free?"你完成了一次真实历史相遇，本次免费并保证获得未拥有人物。":"每次开启消耗60探索星，约对应3次有效学习事件。"}</p><div className="actions"><button className="primary" disabled={complete} onClick={()=>setConfirmDraw(true)}>{complete?"本时期已全部收齐":free?"免费开启第一次人物卡":data.collection.stars>=60?"用60探索星开启":`还差${60-data.collection.stars}探索星`}</button><button className="secondary" onClick={()=>go("hall")}>先看历史展厅</button></div></article><aside className="pack-rules"><article><h3>公开规则</h3><p>白35% · 蓝30% · 紫20% · 橙10% · 金5%。卡级表示本时期策展深度，不评价人物价值。</p></article><article><h3>保底与恢复</h3><p>首次免费保证未拥有。结果先由服务端提交再展示，关闭、刷新或断线不会改变人物。</p></article><article><h3>当前状态</h3><p>已认识 {ownedInPeriod(period)}/12 · 探索星 {data.collection.stars} · 史料碎片 {data.collection.fragments}</p></article></aside></div><section className="section-title"><h2>本卡包12位人物</h2><span>所有人的基本资料都可以浏览</span></section><div className="people-grid">{period.characters.map(character=>personCard(character))}</div></>}
  function chat(){const version=[...messages].reverse().find(message=>message.characterVersion)?.characterVersion??"0.1.0";return <section className="encounter-shell chat-shell"><header className="character-bar">{portrait(selected,"mini")}<div><small>长期线程 · 人物包 v{version}</small><b>{selected.name}</b></div><span className="runtime-mode">{runtimeMode}</span><button className="secondary" onClick={()=>go("person")}>人物简介</button></header><div className="chat-view-options"><span>对话字号</span><div role="group" aria-label="调整对话字号">{(["small","medium","large"] as ChatFontSize[]).map((size,index)=><button type="button" key={size} className={chatFontSize===size?"active":""} aria-pressed={chatFontSize===size} onClick={()=>setChatFontSize(size)}>{["小","中","大"][index]}</button>)}</div></div><div className="chat-workspace" data-font-size={chatFontSize}><div className="chat-main"><div ref={chatScrollRef} className="conversation-stage chat-stage" aria-live="polite" aria-relevant="additions">{messages.length===0&&<p className="empty-state">这是你与{selected.name}长期对话的开始。切换人物再回来，历史仍会保留。</p>}{messages.map((message,index)=><div ref={index===messages.length-1?latestMessageRef:undefined} key={message.id??index} className={`message-row ${message.role==="user"?"user":"character"}`}>{message.role==="character"&&messageAvatar(selected)}<article className={`bubble ${message.role==="user"?"user":"character"}`} aria-label={`${message.role==="user"?"你":selected.name}说`}><p>{message.content}</p>{message.narrator&&<aside className="narrator">博物馆旁白：{message.narrator}</aside>}{message.citations?.map(citation=><small className="citation" key={`${citation.sourceId}:${citation.locator}`}>{citation.title} · {citation.locator}</small>)}</article>{message.role==="user"&&<span className="message-avatar user-avatar" aria-hidden="true">我</span>}</div>)}{busy&&<p className="thinking">正在检索人物记忆与史料…</p>}</div><form className="sample-composer active-composer" onSubmit={event=>{event.preventDefault();void ask()}}><input ref={chatInputRef} value={input} onChange={event=>setInput(event.target.value)} aria-label={`和${selected.name}继续对话`} placeholder={`和${selected.name}继续对话…`}/><button className="primary" disabled={busy||!threadId}>发送</button></form></div><aside className="conversation-memo discovery-panel" data-expanded={memoOpen} aria-label="历史发现"><header><div><small>从对话中发现宝藏</small><h2>历史发现</h2></div><button type="button" className="memo-toggle" aria-expanded={memoOpen} onClick={()=>setMemoOpen(value=>!value)}>{memoOpen?"收起":"展开"}</button></header>{conversationClues.length?<ol>{conversationClues.map(clue=><li key={clue.id}><span>✦ {clue.kind}</span><b>{clue.title}</b><p>{clue.detail}</p></li>)}</ol>:<div className="memo-empty"><b>宝藏还藏在对话里</b><p>聊到代表作品、名句、关键关系或历史事件时，值得收藏的发现会出现在这里。</p></div>}<footer>只记录馆藏策划内容和带来源的史料，不再摘录普通寒暄。</footer></aside></div></section>}

  function bottomNav(){return <nav className="visitor-bottom-nav" aria-label="移动端主要导航"><button className={route==="home"?"active":""} onClick={()=>go("home")}><span>⌂</span>主页</button><button className={["explore","period","hall","encounter","person"].includes(route)?"active":""} onClick={()=>go("explore")}><span>⌕</span>探索</button><button className={["museum","pack","chat"].includes(route)?"active":""} onClick={()=>go("museum")}><span>▣</span>博物馆</button></nav>}
  function settingsPanel(){if(!settingsOpen)return null;return <div className="overlay-bg" onMouseDown={event=>{if(event.target===event.currentTarget)setSettingsOpen(false)}}><section className="settings-panel" role="dialog" aria-modal="true" aria-labelledby="settings-title"><header><div><small>入口与显示</small><h2 id="settings-title">你想去哪里？</h2></div><button className="secondary" onClick={()=>setSettingsOpen(false)} aria-label="关闭入口与显示">关闭</button></header><article><h3>选择视觉主题</h3><p>功能、人物和历史事实完全相同。</p><div className="theme-options"><button className={mode==="child"?"active":"secondary"} aria-pressed={mode==="child"} onClick={()=>setVisualMode("child")}>轻快版</button><button className={mode==="adult"?"active":"secondary"} aria-pressed={mode==="adult"} onClick={()=>setVisualMode("adult")}>典藏版</button></div></article><a className="entry-link" href="/account"><b>账户与进度</b><span>登录、注册或找回密码，让对话与收藏跟随你</span></a><a className="entry-link" href="/"><b>返回选择页面</b><span>重新选择参观方式或进入维护者入口</span></a><a className="entry-link studio-link" href="/studio"><b>进入维护者工作台</b><span>你将离开参观区，管理人物包与史料</span></a></section></div>}

  const views:Record<Route,()=>React.ReactNode>={home,explore,period:periodView,hall:hallView,encounter,person:personView,museum,pack,chat};
  return <main className={`visitor-app ${mode}`} data-mode={mode}>{header()}<div className="visitor-main">{error&&<div className="persistent-error" role="alert"><b>这一步没有完成</b><span>{error}。已保存的数据不会丢失，你可以返回或重试。</span><button onClick={()=>setError("")} aria-label="关闭错误提示">×</button></div>}{views[route]()}</div>{bottomNav()}{settingsPanel()}{notice&&<div className="visitor-toast" role="status">{notice}</div>}{searchOpen&&<div className="overlay-bg" onMouseDown={event=>{if(event.target===event.currentTarget)setSearchOpen(false)}}><section className="search-panel" role="dialog" aria-modal="true" aria-label="搜索人物或关系"><header><input autoFocus value={search} onChange={event=>setSearch(event.target.value)} placeholder="输入人物姓名，例如：爱因斯坦"/><button className="secondary" onClick={()=>setSearchOpen(false)}>关闭</button></header>{search?<><small>人物与关系结果</small><div className="search-results">{searchResults.length?searchResults.map(item=>personCard(item.character,item.reason)):<p className="empty-state">没有找到匹配人物。试试完整姓名或先浏览历史时期。</p>}</div></>:<div className="search-empty"><b>关系搜索不会打断当前页面</b><p>搜索人物后，会先显示本人，再显示与他有正式关系线索的人。</p></div>}</section></div>}{confirmDraw&&<div className="overlay-bg"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="draw-title"><small>结果会先保存</small><h2 id="draw-title">{data.collection.firstFreeEligible&&!data.collection.firstFreeUsed?"使用首次免费开包":"确认开启人物卡"}</h2><p>{data.collection.firstFreeEligible&&!data.collection.firstFreeUsed?"保证获得一位尚未拥有的人物。":"本次消耗60探索星；概率和重复补偿已经公开。"}</p><dl><div><dt>当前探索星</dt><dd>{data.collection.stars} ✦</dd></div><div><dt>本次消耗</dt><dd>{data.collection.firstFreeEligible&&!data.collection.firstFreeUsed?"免费":"60 ✦"}</dd></div></dl><div className="actions"><button className="primary" disabled={busy} onClick={()=>void draw()}>{busy?"正在提交结果…":"确认开启"}</button><button className="secondary" onClick={()=>setConfirmDraw(false)}>先不打开</button></div></section></div>}{drawResult&&<div className="overlay-bg"><section className="modal reveal" role="dialog" aria-modal="true" aria-labelledby="reveal-title"><small>结果已经保存 · 可安全关闭</small><h2 id="reveal-title">{drawResult.duplicate?"再次遇见":"新人物加入你的博物馆"}</h2>{personCard(characters.find(item=>item.id===drawResult.resultCharacterId)!,undefined,false)}{drawResult.duplicate&&<p>重复人物已转化为{drawResult.fragmentReward}个史料碎片。</p>}<div className="actions"><button className="primary" onClick={()=>void acknowledgeDraw("chat")}>开始长期对话</button><button className="secondary" onClick={()=>void acknowledgeDraw("hall")}>先看相关历史</button><button className="quiet" onClick={()=>{setDrawResult(null);go("museum")}}>稍后再看</button></div></section></div>}</main>;
}
