import { describe, expect, it } from "vitest";
import { activeClaims, characterPackSchema, nextPatchVersion, parseCharacterPack, toJsonLd } from "./index.js";

const valid = { manifest: { schemaVersion: "1.0", compatibleRuntime: ">=0.1.0", id: "test-person", version: "1.0.0", name: { "zh-CN": "测试人物" }, author: { id: "author", name: "Author" }, license: { code: "CC0", permissions: [] }, defaultLocale: "zh-CN", bornAt: "1900-01-01", diedAt: "1970-01-01", deceasedEvidenceSourceId: "bio", status: "draft", createdAt: new Date(0).toISOString() }, educationalGoal: "test", boundaries: { knowledgeCutoff: "1970-01-01", allowedTopics: [], limitedTopics: [], forbiddenTopics: [], unknownPatterns: [], modernKnowledgePolicy: "deny" }, persona: { firstPerson: true, languages: ["zh-CN"], tone: [], values: [], ageBands: { "16+": { maxSentences: 5, vocabulary: "advanced", guidance: "" } }, refusalStyle: "不知道", disclaimer: "", examples: [] }, sources: [{ id: "bio", title: "Biography", kind: "book", locale: "zh-CN", license: { code: "CC0", permissions: [] }, locator: "p.1" }], media: [], entities: [{ id: "person", type: "person", names: { "zh-CN": "测试人物" } }], claims: [{ id: "c1", subjectId: "person", predicate: "出生", value: "1900年出生", status: "established", confidence: 1, evidence: [{ sourceId: "bio", locator: "p.1" }], topicIds: [], approved: true, perspective: "character" }], relationships: [], evaluations: [] };
describe("character pack", () => {
  it("validates traceability and JSON-LD round trip identity", () => { const pack = parseCharacterPack(valid); expect(characterPackSchema.safeParse(pack).success).toBe(true); expect(JSON.stringify(parseCharacterPack(JSON.parse(JSON.stringify(pack))))).toBe(JSON.stringify(pack)); expect(JSON.stringify(toJsonLd(pack))).toContain("c1"); });
  it("rejects claims without a live source", () => { const broken = structuredClone(valid); broken.claims[0].evidence[0].sourceId = "missing"; expect(characterPackSchema.safeParse(broken).success).toBe(false); });
  it("increments immutable versions", () => expect(nextPatchVersion("1.2.9")).toBe("1.2.10"));
  it("keeps revoked history but removes unsupported claims from the answer index", () => { const revoked: any = structuredClone(valid); revoked.sources.push({ ...revoked.sources[0], id: "evidence", revokedAt: new Date().toISOString() }); revoked.claims[0].evidence[0].sourceId = "evidence"; const pack = parseCharacterPack(revoked); expect(activeClaims(pack)).toHaveLength(0); });
});
