import { randomUUID } from "node:crypto";
import { z } from "zod";
import type { AgentArtifact, AgentStep, AgentTask, AgentTaskType } from "@ai-museum/sdk";
import { getPublishedPack, listPacks } from "./repository";
import { addArtifact, createTask, getTask, listMastery, listThreads, updateTask } from "./platform-store";

const taskInputSchema = z.object({ type: z.enum(["guide", "media", "knowledge", "evaluation"]), input: z.record(z.unknown()).default({}), consentId: z.string().optional() });
const allowedTools = new Set(["read_mastery", "list_thread_summaries", "read_character_pack", "inspect_asset_metadata", "run_pack_evaluations", "create_artifact"]);
function step(name: string, tool?: string): AgentStep { if (tool && !allowedTools.has(tool)) throw new Error(`Tool not allowed: ${tool}`); return { id: randomUUID(), name, status: "pending", tool }; }
function plan(type: AgentTaskType): AgentStep[] { if (type === "guide") return [step("读取学习进度", "read_mastery"), step("读取人物线程摘要", "list_thread_summaries"), step("生成学习路线", "create_artifact")]; if (type === "knowledge") return [step("检查素材元数据", "inspect_asset_metadata"), step("规划受控提取流程"), step("生成待审核报告", "create_artifact")]; if (type === "evaluation") return [step("读取人物包", "read_character_pack"), step("运行人物包评测", "run_pack_evaluations"), step("生成评测报告", "create_artifact")]; return [step("检查人物与访问者授权"), step("检索时代与场景依据", "read_character_pack"), step("生成合影任务")]; }
function artifact(task: AgentTask, kind: AgentArtifact["kind"], name: string, data: unknown) { const value: AgentArtifact = { id: randomUUID(), taskId: task.id, kind, name, contentType: "application/json", data, createdAt: new Date().toISOString() }; addArtifact(value); task.artifactIds.push(value.id); return value; }
function completeStep(item: AgentStep, detail: string) { const now = new Date().toISOString(); item.status = "completed"; item.startedAt ??= now; item.completedAt = now; item.detail = detail; }

export function startAgentTask(userId: string, raw: unknown) {
  const request = taskInputSchema.parse(raw); const now = new Date().toISOString(); const task: AgentTask = { id: randomUUID(), type: request.type, status: "queued", input: request.input, plan: plan(request.type), currentStep: 0, artifactIds: [], provider: "rules", model: "deterministic-local", attempt: 0, createdBy: userId, consentId: request.consentId, resumeToken: randomUUID(), createdAt: now, updatedAt: now };
  createTask(task); return runTask(task, userId);
}
export function runTask(task: AgentTask, userId: string) {
  if (task.status === "cancelled" || task.status === "completed") return task; task.status = "planning"; task.attempt++; updateTask(task);
  try {
    task.status = "running";
    if (task.type === "guide") { const mastery = listMastery(userId); const threads = listThreads(userId); completeStep(task.plan[0], `读取 ${mastery.length} 项知识状态`); completeStep(task.plan[1], `读取 ${threads.length} 个人物线程摘要`); const topic = String(task.input.topic ?? "科学史"); const recommendations = listPacks().slice(0, 4).map((pack, index) => ({ order: index + 1, characterId: pack.manifest.id, name: pack.manifest.name[pack.manifest.defaultLocale], reason: index === 0 ? `从核心人物进入${topic}` : `从不同人物视角补充${topic}` })); artifact(task, "learning-plan", `${topic}学习路线`, { topic, recommendations, mastery: mastery.map(item => ({ topicId: item.topicId, level: item.level })) }); completeStep(task.plan[2], "学习路线已生成"); }
    if (task.type === "knowledge") { completeStep(task.plan[0], "仅检查已登记素材，不抓取未授权外部内容"); completeStep(task.plan[1], "OCR/转录/实体与 Claim 提取需要受控 Provider"); artifact(task, "knowledge-report", "知识加工待审核报告", { status: "waiting_review", note: "规则模式不会自动产生正式 Claim", input: task.input }); completeStep(task.plan[2], "候选报告已生成，必须人工审核"); task.status = "waiting_review"; updateTask(task); return task; }
    if (task.type === "evaluation") { const characterId = String(task.input.characterId ?? "albert-einstein"); const pack = getPublishedPack(characterId); if (!pack) throw Object.assign(new Error("人物包不存在"), { code: "PACK_NOT_FOUND" }); completeStep(task.plan[0], `读取人物包 ${pack.manifest.version}`); const report = pack.evaluations.map(test => ({ id: test.id, prompt: test.prompt, expectedBoundary: test.expectedBoundary, status: "defined" })); completeStep(task.plan[1], `检查 ${report.length} 项评测定义`); artifact(task, "evaluation-report", `${characterId}评测报告`, { characterId, version: pack.manifest.version, tests: report, note: "规则模式完成结构检查；模型回归需配置 AgentModelProvider" }); completeStep(task.plan[2], "评测报告已生成"); }
    if (task.type === "media") { if (!task.consentId) { task.status = "waiting_review"; task.errorCode = "CONSENT_REQUIRED"; task.plan[0].status = "pending"; task.plan[0].detail = "需要访问者肖像用途授权"; updateTask(task); return task; } completeStep(task.plan[0], "已记录访问者肖像授权"); const characterId = String(task.input.characterId ?? ""); const pack = getPublishedPack(characterId); if (!pack) throw Object.assign(new Error("人物包不存在"), { code: "PACK_NOT_FOUND" }); const likenessAllowed = pack.media.some(media => media.license.permissions.includes("likeness-generation")); if (!likenessAllowed) throw Object.assign(new Error("人物包未授权形象生成"), { code: "LIKENESS_NOT_ALLOWED" }); completeStep(task.plan[1], "人物形象与史料授权检查通过"); throw Object.assign(new Error("尚未配置 ImageGenerationProvider"), { code: "PROVIDER_NOT_CONFIGURED" }); }
    task.currentStep = task.plan.length; task.status = "completed";
  } catch (error) { task.status = "failed"; task.errorCode = typeof error === "object" && error && "code" in error ? String(error.code) : "AGENT_FAILED"; const current = task.plan.find(item => item.status === "pending" || item.status === "running"); if (current) { current.status = "failed"; current.detail = error instanceof Error ? error.message : "任务失败"; } }
  return updateTask(task);
}
export function confirmTask(userId: string, taskId: string, consentId?: string) { const task = getTask(taskId, userId); if (!task) return null; if (task.status !== "waiting_review") throw new Error("任务不在等待确认状态"); if(task.type==="knowledge"){task.status="completed";task.currentStep=task.plan.length;task.errorCode=undefined;return updateTask(task);} task.consentId = consentId ?? task.consentId; task.errorCode = undefined; task.status = "queued"; task.resumeToken = randomUUID(); return runTask(task, userId); }
export function cancelTask(userId: string, taskId: string) { const task = getTask(taskId, userId); if (!task) return null; if (["completed", "cancelled"].includes(task.status)) return task; task.status = "cancelled"; return updateTask(task); }
export function retryTask(userId:string,taskId:string){const task=getTask(taskId,userId);if(!task)return null;if(task.status!=="failed")throw new Error("只有失败任务可以重试");if(task.attempt>=3)throw new Error("任务已达到最大重试次数");task.status="queued";task.errorCode=undefined;task.resumeToken=randomUUID();task.plan.forEach(item=>{if(item.status==="failed"){item.status="pending";item.detail=undefined}});return runTask(task,userId)}
