import { beforeEach, describe, expect, it } from "vitest";
import { activeCharacterMemories, addMessage, createMemory, getOrCreateThread, listMessages, listThreads, mergeGuestIntoUser, platform, resetPlatformForTests, upgradeThread } from "./platform-store";
beforeEach(resetPlatformForTests);
describe("persistent conversation scopes", () => {
  it("keeps one continuous thread per user and character", () => { const first=getOrCreateThread("u1","einstein","1.0.0","Einstein");const again=getOrCreateThread("u1","einstein","1.0.0","Einstein");const bohr=getOrCreateThread("u1","bohr","0.1.0","Bohr");expect(again.id).toBe(first.id);expect(bohr.id).not.toBe(first.id); });
  it("stores messages inside their owning thread only", () => { const einstein=getOrCreateThread("u1","einstein","1.0.0","Einstein");const bohr=getOrCreateThread("u1","bohr","0.1.0","Bohr");addMessage(einstein,{role:"user",content:"玻尔",claimIds:[],citations:[]});expect(listMessages(einstein.id,"u1")?.messages).toHaveLength(1);expect(listMessages(bohr.id,"u1")?.messages).toHaveLength(0);expect(listMessages(einstein.id,"u2")).toBeNull(); });
  it("isolates memories and excludes unconfirmed sensitive candidates", () => { createMemory({userId:"u1",characterId:"einstein",type:"character_relationship",content:"聊过玻尔",sourceMessageIds:["m1"],confidence:.8,importance:.7,sensitivity:"low",status:"active"});createMemory({userId:"u1",characterId:"einstein",type:"preference",content:"敏感资料",sourceMessageIds:["m2"],confidence:.8,importance:.7,sensitivity:"sensitive",status:"pending_confirmation"});expect(activeCharacterMemories("u1","einstein")).toHaveLength(1);expect(activeCharacterMemories("u1","bohr")).toHaveLength(0); });
  it("consolidates repeated relationship memories and appends sources", () => { const base={userId:"u1",characterId:"einstein",type:"character_relationship" as const,content:"聊过玻尔",confidence:.8,importance:.7,sensitivity:"low" as const,status:"active" as const};createMemory({...base,sourceMessageIds:["m1"]});createMemory({...base,sourceMessageIds:["m2"]});expect(activeCharacterMemories("u1","einstein")).toHaveLength(1);expect(activeCharacterMemories("u1","einstein")[0].sourceMessageIds).toEqual(["m1","m2"]); });
  it("creates an epoch on explicit version upgrade", () => { const thread=getOrCreateThread("u1","einstein","1.0.0","Einstein");const old=thread.currentEpochId;upgradeThread(thread,"1.1.0");expect(thread.currentEpochId).not.toBe(old);expect(platform.epochs.find(epoch=>epoch.id===old)?.endedAt).toBeTruthy(); });
  it("merges a guest idempotently without duplicating messages", () => { const guest=getOrCreateThread("guest:x","einstein","1.0.0","Einstein");addMessage(guest,{role:"user",content:"hello",claimIds:[],citations:[]});mergeGuestIntoUser("guest:x","account:1");mergeGuestIntoUser("guest:x","account:1");expect(listThreads("account:1")).toHaveLength(1);expect(listMessages(guest.id,"account:1")?.messages).toHaveLength(1); });
});
