import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import type { AgentArtifact, AgentTask, ConversationMessage, ConversationThread, MasteryRecord, MemoryRecord, ThreadEpoch } from "@ai-museum/sdk";

export interface CollectionRecord { userId: string; ownedCharacterIds: string[]; stars: number; fragments: number; firstFreeEligible: boolean; firstFreeUsed: boolean; revision: number; updatedAt: string }
export interface LearningEventRecord { id: string; userId: string; characterId: string; periodId: string; type: "evidence_viewed" | "encounter_completed" | "meaningful_question"; idempotencyKey: string; rewardStars: number; createdAt: string }
export interface DrawRecord { id: string; userId: string; periodId: string; idempotencyKey: string; costStars: number; resultCharacterId: string; duplicate: boolean; fragmentReward: number; status: "committed" | "revealed"; createdAt: string; revealedAt?: string }

interface PlatformState { threads: ConversationThread[]; epochs: ThreadEpoch[]; messages: ConversationMessage[]; memories: MemoryRecord[]; mastery: MasteryRecord[]; tasks: AgentTask[]; artifacts: AgentArtifact[]; collections: CollectionRecord[]; learningEvents: LearningEventRecord[]; draws: DrawRecord[] }
const empty = (): PlatformState => ({ threads: [], epochs: [], messages: [], memories: [], mastery: [], tasks: [], artifacts: [], collections: [], learningEvents: [], draws: [] });
const runtimeDir = path.join(process.cwd(), "..", "..", "data", "runtime");
const stateFile = path.join(runtimeDir, process.env.VITEST ? "platform.test.json" : "platform.json");
function load(): PlatformState { try { if (existsSync(stateFile)) return { ...empty(), ...JSON.parse(readFileSync(stateFile, "utf8")) }; } catch { /* Recover with a clean local store; production uses PostgreSQL. */ } return empty(); }
const globals = globalThis as typeof globalThis & { __platformState?: PlatformState };
export const platform = globals.__platformState ??= load();
function persist() { mkdirSync(runtimeDir, { recursive: true }); const temp = `${stateFile}.tmp`; writeFileSync(temp, JSON.stringify(platform, null, 2), "utf8"); writeFileSync(stateFile, readFileSync(temp)); }
export function resetPlatformForTests() { Object.assign(platform, empty()); }

export function getOrCreateThread(userId: string, characterId: string, characterVersion: string, title: string) {
  const existing = platform.threads.find(thread => thread.userId === userId && thread.characterId === characterId); if (existing) return existing;
  const now = new Date().toISOString(); const threadId = randomUUID(); const epoch: ThreadEpoch = { id: randomUUID(), threadId, characterVersion, startedAt: now };
  const thread: ConversationThread = { id: threadId, userId, characterId, currentEpochId: epoch.id, characterVersion, title, createdAt: now, updatedAt: now };
  platform.threads.push(thread); platform.epochs.push(epoch); persist(); return thread;
}
export function listThreads(userId: string) { return platform.threads.filter(thread => thread.userId === userId).sort((a, b) => (b.lastMessageAt ?? b.updatedAt).localeCompare(a.lastMessageAt ?? a.updatedAt)); }
export function getThreadForUser(threadId: string, userId: string) { return platform.threads.find(thread => thread.id === threadId && thread.userId === userId) ?? null; }
export function listMessages(threadId: string, userId: string, cursor?: string, limit = 50) { if (!getThreadForUser(threadId, userId)) return null; const all = platform.messages.filter(message => message.threadId === threadId); const end = cursor ? Math.max(0, all.findIndex(message => message.id === cursor)) : all.length; const start = Math.max(0, end - Math.min(limit, 100)); return { messages: all.slice(start, end), nextCursor: start > 0 ? all[start].id : undefined }; }
export function addMessage(thread: ConversationThread, input: Omit<ConversationMessage, "id" | "threadId" | "epochId" | "characterVersion" | "createdAt">) { const message: ConversationMessage = { ...input, id: randomUUID(), threadId: thread.id, epochId: thread.currentEpochId, characterVersion: thread.characterVersion, createdAt: new Date().toISOString() }; platform.messages.push(message); thread.lastMessageAt = message.createdAt; thread.updatedAt = message.createdAt; if (input.role === "user") thread.summary = input.content.slice(0, 100); persist(); return message; }
export function upgradeThread(thread: ConversationThread, version: string) { if (thread.characterVersion === version) return thread; const now = new Date().toISOString(); const current = platform.epochs.find(epoch => epoch.id === thread.currentEpochId); if (current) current.endedAt = now; const epoch: ThreadEpoch = { id: randomUUID(), threadId: thread.id, characterVersion: version, startedAt: now }; platform.epochs.push(epoch); thread.currentEpochId = epoch.id; thread.characterVersion = version; thread.updatedAt = now; persist(); return thread; }

export function listMemories(userId: string, characterId?: string) { return platform.memories.filter(memory => memory.userId === userId && (characterId === undefined || memory.characterId === characterId)); }
export function activeCharacterMemories(userId: string, characterId: string) { return platform.memories.filter(memory => memory.userId === userId && memory.characterId === characterId && memory.status === "active"); }
export function createMemory(input: Omit<MemoryRecord, "id" | "recallCount" | "createdAt" | "updatedAt">) { const duplicate = platform.memories.find(memory => memory.userId === input.userId && memory.characterId === input.characterId && memory.type === input.type && memory.content === input.content && memory.status !== "forgotten"); if (duplicate) { duplicate.sourceMessageIds=[...new Set([...duplicate.sourceMessageIds,...input.sourceMessageIds])];duplicate.confidence=Math.max(duplicate.confidence,input.confidence);duplicate.importance=Math.max(duplicate.importance,input.importance);duplicate.updatedAt=new Date().toISOString();persist();return duplicate; } const now = new Date().toISOString(); const memory: MemoryRecord = { ...input, id: randomUUID(), recallCount: 0, createdAt: now, updatedAt: now }; platform.memories.push(memory); persist(); return memory; }
export function updateMemory(id: string, userId: string, patch: Partial<Pick<MemoryRecord, "content" | "status" | "importance" | "confidence">>) { const memory = platform.memories.find(item => item.id === id && item.userId === userId); if (!memory) return null; Object.assign(memory, patch, { updatedAt: new Date().toISOString() }); persist(); return memory; }
export function recallMemory(memory: MemoryRecord) { memory.recallCount++; memory.lastRecalledAt = new Date().toISOString(); memory.updatedAt = memory.lastRecalledAt; persist(); }

export function listMastery(userId: string) { return platform.mastery.filter(record => record.userId === userId); }
export function exposeTopic(userId: string, topicId: string, messageIds: string[]) { let record = platform.mastery.find(item => item.userId === userId && item.topicId === topicId); const now = new Date().toISOString(); if (!record) { record = { id: randomUUID(), userId, topicId, level: "exposed", confidence: .25, evidenceMessageIds: messageIds, lastPracticedAt: now, updatedAt: now }; platform.mastery.push(record); } else { record.evidenceMessageIds = [...new Set([...record.evidenceMessageIds, ...messageIds])]; record.lastPracticedAt = now; record.updatedAt = now; if (record.level === "new" || record.level === "decayed") record.level = "exposed"; } persist(); return record; }
export function updateMastery(id: string, userId: string, level: MasteryRecord["level"]) { const record = platform.mastery.find(item => item.id === id && item.userId === userId); if (!record) return null; record.level = level; record.confidence = level === "mastered" ? .9 : level === "practicing" ? .6 : .3; record.updatedAt = new Date().toISOString(); persist(); return record; }

const initialOwnedCharacterIds = ["li-bai", "wu-zetian", "leonardo-da-vinci", "raphael", "albert-einstein", "niels-bohr", "marie-curie", "max-planck"];
export function getOrCreateCollection(userId: string) { let record = platform.collections.find(item => item.userId === userId); if (record) return record; record = { userId, ownedCharacterIds: [...initialOwnedCharacterIds], stars: 60, fragments: 20, firstFreeEligible: false, firstFreeUsed: false, revision: 1, updatedAt: new Date().toISOString() }; platform.collections.push(record); persist(); return record; }
export function findLearningEvent(userId: string, idempotencyKey: string) { return platform.learningEvents.find(item => item.userId === userId && item.idempotencyKey === idempotencyKey) ?? null; }
export function findCharacterLearningEvent(userId: string, characterId: string, type: LearningEventRecord["type"]) { return platform.learningEvents.find(item => item.userId === userId && item.characterId === characterId && item.type === type) ?? null; }
export function addLearningEvent(event: LearningEventRecord) { platform.learningEvents.push(event); persist(); return event; }
export function findDraw(userId: string, idempotencyKey: string) { return platform.draws.find(item => item.userId === userId && item.idempotencyKey === idempotencyKey) ?? null; }
export function addDraw(draw: DrawRecord) { platform.draws.push(draw); persist(); return draw; }
export function getDraw(id: string, userId: string) { return platform.draws.find(item => item.id === id && item.userId === userId) ?? null; }
export function latestCommittedDraw(userId: string) { return platform.draws.filter(item => item.userId === userId && item.status === "committed").sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0] ?? null; }
export function saveExplorationState() { persist(); }

export function createTask(task: AgentTask) { platform.tasks.push(task); persist(); return task; }
export function updateTask(task: AgentTask) { task.updatedAt = new Date().toISOString(); persist(); return task; }
export function getTask(id: string, userId: string) { return platform.tasks.find(task => task.id === id && task.createdBy === userId) ?? null; }
export function listTasks(userId: string) { return platform.tasks.filter(task => task.createdBy === userId).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); }
export function addArtifact(artifact: AgentArtifact) { platform.artifacts.push(artifact); persist(); return artifact; }
export function getArtifact(id: string, userId: string) { const artifact = platform.artifacts.find(item => item.id === id); if (!artifact) return null; return getTask(artifact.taskId, userId) ? artifact : null; }

export function mergeGuestIntoUser(guestId: string, userId: string) { if (guestId === userId) return; for (const thread of platform.threads.filter(item => item.userId === guestId)) { const target = platform.threads.find(item => item.userId === userId && item.characterId === thread.characterId); if (target) { for (const message of platform.messages.filter(item => item.threadId === thread.id)) message.threadId = target.id; platform.epochs.filter(item => item.threadId === thread.id).forEach(epoch => epoch.threadId = target.id); platform.threads.splice(platform.threads.indexOf(thread), 1); } else thread.userId = userId; } platform.memories.filter(item => item.userId === guestId).forEach(item => item.userId = userId); platform.mastery.filter(item => item.userId === guestId).forEach(item => item.userId = userId); platform.tasks.filter(item => item.createdBy === guestId).forEach(item => item.createdBy = userId); const guestCollection=platform.collections.find(item=>item.userId===guestId);const userCollection=platform.collections.find(item=>item.userId===userId);if(guestCollection&&userCollection){userCollection.ownedCharacterIds=[...new Set([...userCollection.ownedCharacterIds,...guestCollection.ownedCharacterIds])];userCollection.stars+=guestCollection.stars;userCollection.fragments+=guestCollection.fragments;userCollection.firstFreeEligible ||= guestCollection.firstFreeEligible;userCollection.firstFreeUsed ||= guestCollection.firstFreeUsed;platform.collections.splice(platform.collections.indexOf(guestCollection),1)}else if(guestCollection)guestCollection.userId=userId; platform.learningEvents.filter(item=>item.userId===guestId).forEach(item=>item.userId=userId);platform.draws.filter(item=>item.userId===guestId).forEach(item=>item.userId=userId); persist(); }
