import { beforeEach,describe,expect,it } from "vitest";
import { activeCharacterMemories,addMessage,createMemory,getOrCreateThread,listMessages,listThreads,mergeGuestIntoUser,platform,resetPlatformForTests,saveHallVisit,upgradeThread } from "./platform-store";
beforeEach(resetPlatformForTests);
describe("persistent conversation scopes",()=>{
  it("keeps one continuous thread per user and character",async()=>{const first=await getOrCreateThread("u1","einstein","1.0.0","Einstein");const again=await getOrCreateThread("u1","einstein","1.0.0","Einstein");const bohr=await getOrCreateThread("u1","bohr","0.1.0","Bohr");expect(again.id).toBe(first.id);expect(bohr.id).not.toBe(first.id);});
  it("stores messages inside their owning thread only",async()=>{const einstein=await getOrCreateThread("u1","einstein","1.0.0","Einstein");const bohr=await getOrCreateThread("u1","bohr","0.1.0","Bohr");await addMessage(einstein,{role:"user",content:"玻尔",claimIds:[],citations:[]});expect((await listMessages(einstein.id,"u1"))?.messages).toHaveLength(1);expect((await listMessages(bohr.id,"u1"))?.messages).toHaveLength(0);expect(await listMessages(einstein.id,"u2")).toBeNull();});
  it("isolates memories and excludes unconfirmed sensitive candidates",async()=>{await createMemory({userId:"u1",characterId:"einstein",type:"character_relationship",content:"聊过玻尔",sourceMessageIds:["m1"],confidence:.8,importance:.7,sensitivity:"low",status:"active"});await createMemory({userId:"u1",characterId:"einstein",type:"preference",content:"敏感资料",sourceMessageIds:["m2"],confidence:.8,importance:.7,sensitivity:"sensitive",status:"pending_confirmation"});expect(await activeCharacterMemories("u1","einstein")).toHaveLength(1);expect(await activeCharacterMemories("u1","bohr")).toHaveLength(0);});
  it("consolidates repeated relationship memories and appends sources",async()=>{const base={userId:"u1",characterId:"einstein",type:"character_relationship" as const,content:"聊过玻尔",confidence:.8,importance:.7,sensitivity:"low" as const,status:"active" as const};await createMemory({...base,sourceMessageIds:["m1"]});await createMemory({...base,sourceMessageIds:["m2"]});const memories=await activeCharacterMemories("u1","einstein");expect(memories).toHaveLength(1);expect(memories[0].sourceMessageIds).toEqual(["m1","m2"]);});
  it("creates an epoch on explicit version upgrade",async()=>{const thread=await getOrCreateThread("u1","einstein","1.0.0","Einstein");const old=thread.currentEpochId;await upgradeThread(thread,"1.1.0");expect(thread.currentEpochId).not.toBe(old);expect(platform.epochs.find(epoch=>epoch.id===old)?.endedAt).toBeTruthy();});
  it("merges a guest idempotently without duplicating messages",async()=>{const guest=await getOrCreateThread("guest:x","einstein","1.0.0","Einstein");await addMessage(guest,{role:"user",content:"hello",claimIds:[],citations:[]});await mergeGuestIntoUser("guest:x","account:1");await mergeGuestIntoUser("guest:x","account:1");expect(await listThreads("account:1")).toHaveLength(1);expect((await listMessages(guest.id,"account:1"))?.messages).toHaveLength(1);});
});
describe("hall visit progress",()=>{
  it("detects a stale revision and merges the retried id sets",async()=>{const base={userId:"u1",hallId:"physics-solvay",sceneVersion:"1.0.0",lastStationId:"orientation",viewedObjectIds:[],visitedCharacterIds:[],completedStationIds:[]};const first=await saveHallVisit(base);expect(first.conflict).toBe(false);const stale=await saveHallVisit({...base,lastStationId:"object",viewedObjectIds:["physics-solvay-anchor"],expectedRevision:0});expect(stale.conflict).toBe(true);const retried=await saveHallVisit({...base,lastStationId:"characters",viewedObjectIds:["physics-solvay-anchor"],visitedCharacterIds:["albert-einstein"],expectedRevision:stale.state.revision});expect(retried.conflict).toBe(false);expect(retried.state.viewedObjectIds).toEqual(["physics-solvay-anchor"]);expect(retried.state.visitedCharacterIds).toEqual(["albert-einstein"]);});
});
