import { einsteinPack, supportingPacks } from "@ai-museum/characters";
import { nextPatchVersion, parseCharacterPack, type CandidateClaim, type CharacterPack, type IngestionJob, type SourceAsset } from "@ai-museum/sdk";

type State = { packs: Map<string, CharacterPack[]>; assets: Map<string, SourceAsset>; candidates: Map<string, CandidateClaim>; jobs: Map<string, IngestionJob>; reviewLocks: Set<string> };
const globals = globalThis as typeof globalThis & { __museum?: State };
function fresh(): State { return { packs: new Map([einsteinPack, ...supportingPacks].map(p => [p.manifest.id, [structuredClone(p)]])), assets: new Map(), candidates: new Map(), jobs: new Map(), reviewLocks: new Set() }; }
export const store = globals.__museum ??= fresh();
export function resetStoreForTests() { globals.__museum = undefined; }
export function listPacks(includeDrafts = false) { return [...store.packs.values()].flatMap(v => v.at(-1) ?? []).filter(p => includeDrafts || p.manifest.status === "published"); }
export function getPack(id: string, version?: string) { const all = store.packs.get(id) ?? []; return version ? all.find(p => p.manifest.version === version) ?? null : all.at(-1) ?? null; }
export function getPublishedPack(id: string, version?: string) { const all = (store.packs.get(id) ?? []).filter(p => p.manifest.status === "published"); return version ? all.find(p => p.manifest.version === version) ?? null : all.at(-1) ?? null; }
export function saveNewVersion(input: unknown) { const pack = parseCharacterPack(input); const all = store.packs.get(pack.manifest.id) ?? []; if (all.some(p => p.manifest.version === pack.manifest.version)) throw new Error("该版本已存在；发布版本不可覆盖"); store.packs.set(pack.manifest.id, [...all, structuredClone(pack)]); return pack; }
export function saveDraft(input: unknown) { const pack = parseCharacterPack(input); if (pack.manifest.status !== "draft") return saveNewVersion(pack); const all = store.packs.get(pack.manifest.id) ?? []; const index = all.findIndex(p => p.manifest.version === pack.manifest.version); if (index >= 0 && all[index].manifest.status !== "draft") throw new Error("不可覆盖非草稿版本"); const next = [...all]; if (index >= 0) next[index] = structuredClone(pack); else next.push(structuredClone(pack)); store.packs.set(pack.manifest.id, next); return pack; }
export function createDraft(body: Record<string, unknown>) {
  const id = String(body.id ?? "").trim().toLowerCase(); const name = String(body.name ?? "").trim(); const bornAt = String(body.bornAt ?? ""); const diedAt = String(body.diedAt ?? "");
  if (!/^[a-z0-9-]+$/.test(id) || !name || !bornAt || !diedAt) throw new Error("人物ID、名称及生卒日期必填"); if (Date.parse(diedAt) >= Date.now()) throw new Error("公共人物必须为已故人物");
  const sourceId = "identity-evidence"; const entityId = `${id}-person`; const now = new Date().toISOString();
  return saveDraft({ manifest: { schemaVersion: "1.0", compatibleRuntime: ">=0.1.0", id, version: "0.1.0", name: { "zh-CN": name }, author: { id: String(body.authorId ?? "local-creator"), name: String(body.authorName ?? "本地创建者") }, license: { code: String(body.license ?? "PRIVATE"), permissions: [] }, defaultLocale: "zh-CN", bornAt, diedAt, deceasedEvidenceSourceId: sourceId, status: "draft", createdAt: now }, educationalGoal: String(body.educationalGoal ?? ""), boundaries: { knowledgeCutoff: diedAt, allowedTopics: String(body.allowedTopics ?? "人物生平").split(/[，,]/).filter(Boolean), limitedTopics: [], forbiddenTopics: ["医疗建议", "投资建议", "仇恨或暴力", "他人隐私"], unknownPatterns: ["身后事件"], modernKnowledgePolicy: "museum-narrator" }, persona: { firstPerson: true, languages: ["zh-CN"], tone: ["克制"], values: ["证据"], ageBands: { "6-8": { maxSentences: 3, vocabulary: "simple", guidance: "短句" }, "9-12": { maxSentences: 5, vocabulary: "standard", guidance: "解释术语" }, "13-15": { maxSentences: 7, vocabulary: "standard", guidance: "说明证据" }, "16+": { maxSentences: 10, vocabulary: "advanced", guidance: "保留语境" } }, refusalStyle: "这超出了我有可靠史料支持的认知范围。", disclaimer: "基于史料的教育性角色演绎。", examples: [] }, sources: [{ id: sourceId, title: String(body.identityEvidenceTitle ?? "创建者提供的身份依据"), kind: "web", url: String(body.identityEvidenceUrl ?? "https://example.org/identity-evidence"), locale: "zh-CN", license: { code: "LINK-ONLY", permissions: ["display"] }, locator: "人物身份与生卒信息" }], media: [], entities: [{ id: entityId, type: "person", names: { "zh-CN": name }, bornAt, diedAt }], claims: [], relationships: [], evaluations: [] });
}
export function forkPack(id: string, authorId: string, authorName: string) { const source = getPublishedPack(id); if (!source) throw new Error("只能 Fork 已发布人物包"); const forkId = `${id}-${authorId.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`; const fork = structuredClone(source); fork.manifest = { ...fork.manifest, id: forkId, version: "0.1.0", status: "draft", author: { id: authorId, name: authorName }, forkedFrom: { id, version: source.manifest.version, authorId: source.manifest.author.id }, createdAt: new Date().toISOString(), publishedAt: undefined }; return saveDraft(fork); }
export function submitPack(id: string) { const pack = getPack(id); if (!pack || pack.manifest.status !== "draft") throw new Error("只可提交当前草稿"); if (!pack.claims.length || pack.claims.some(c => !c.approved)) throw new Error("所有 Claim 必须人工审核且至少有一条"); if (!pack.evaluations.length) throw new Error("提交前至少需要一项边界或事实评测"); pack.manifest.status = "submitted"; return pack; }
export function publishPack(id: string) { const pack = getPack(id); if (!pack || pack.manifest.status !== "submitted") throw new Error("人物包尚未提交审核"); pack.manifest.status = "published"; pack.manifest.publishedAt = new Date().toISOString(); return pack; }
export function createUpgrade(id: string) { const current = getPublishedPack(id); if (!current) throw new Error("人物不存在"); const draft = structuredClone(current); draft.manifest.version = nextPatchVersion(current.manifest.version); draft.manifest.status = "draft"; draft.manifest.createdAt = new Date().toISOString(); draft.manifest.publishedAt = undefined; return saveNewVersion(draft); }
export function attachAcceptedCandidate(id: string, decision: "accepted" | "rejected", expectedRevision: number, edits?: Partial<CandidateClaim>) { const candidate = store.candidates.get(id); if (!candidate) throw new Error("候选 Claim 不存在"); if (store.reviewLocks.has(id)) throw new Error("该候选正在被审核"); store.reviewLocks.add(id); try { if (candidate.revision !== expectedRevision) throw new Error("候选已被其他审核者更新"); if (candidate.reviewStatus !== "pending") return candidate; Object.assign(candidate, edits ?? {}); candidate.reviewStatus = decision; candidate.revision++; if (decision === "accepted") { const pack = getPack(store.assets.get(candidate.assetId)?.characterId ?? ""); if (!pack || pack.manifest.status !== "draft") throw new Error("目标草稿不存在"); pack.claims.push({ id: candidate.id, subjectId: candidate.subjectId, predicate: candidate.predicate, objectId: candidate.objectId, value: candidate.value, validFrom: candidate.validFrom, validTo: candidate.validTo, status: candidate.status, confidence: candidate.confidence, evidence: candidate.evidence, topicIds: candidate.topicIds, approved: true, perspective: candidate.perspective }); } return candidate; } finally { store.reviewLocks.delete(id); } }
