import { describe, expect, it } from "vitest";
import { einsteinPack, supportingPacks } from "@ai-museum/characters";
import { runDialogue, type DialogueGenerator } from "./runtime";
const request = { characterId: "albert-einstein", message: "为什么获得诺贝尔奖？光电效应", ageBand: "9-12", locale: "zh-CN" };
describe("verified dialogue runtime", () => {
  it("returns claims with exact evidence locators", async () => { const result = await runDialogue(einsteinPack, request); expect(result.claimIds).toContain("claim-nobel"); expect(result.citations).toContainEqual(expect.objectContaining({ sourceId: "nobel-award", locator: "Prize motivation" })); });
  it("rejects a generator that cites knowledge outside retrieval", async () => { const bad: DialogueGenerator = { mode:"cloud-model",async generate() { return { answer: "越权内容", claimIds: ["claim-born"] }; } }; const result = await runDialogue(einsteinPack, request, bad); expect(result.boundary).toBe(true); expect(result.classification).toBe("引用核验失败"); });
  it("allows cloud-model character dialogue without a matching Claim", async () => { const cloud:DialogueGenerator={mode:"cloud-model",async generate(){return{answer:"我是阿尔伯特·爱因斯坦。我们可以从一个思想实验开始。",claimIds:[],mode:"cloud-model"}}};const result=await runDialogue(einsteinPack,{...request,message:"你是谁？"},cloud);expect(result.boundary).toBe(false);expect(result.classification).toBe("模型角色演绎");expect(result.citations).toHaveLength(0);expect(result.mode).toBe("cloud-model"); });
  it("discloses the AI representation deterministically in every provider mode",async()=>{const cloud:DialogueGenerator={mode:"cloud-model",async generate(){throw new Error("identity disclosure must not depend on the model")}};const result=await runDialogue(einsteinPack,{...request,message:"你是真人还是AI？"},cloud);expect(result.classification).toBe("身份透明");expect(result.answer).toMatch(/AI Museum/);expect(result.answer).toMatch(/不是历史人物本人/);});
  it("blocks concepts that did not exist within the character lifetime",async()=>{const liBai=supportingPacks.find(pack=>pack.manifest.id==="li-bai")!;const cloud:DialogueGenerator={mode:"cloud-model",async generate(){throw new Error("boundary must run before model")}};const result=await runDialogue(liBai,{...request,characterId:"li-bai",message:"李白，你会不会微积分？"},cloud);expect(result.boundary).toBe(true);expect(result.classification).toBe("after-lifetime");expect(result.answer).toMatch(/不装作知晓/);expect(result.mode).toBe("cloud-model");});
  it("attaches public relationship evidence when another character is named",async()=>{const liBai=supportingPacks.find(pack=>pack.manifest.id==="li-bai")!;const cloud:DialogueGenerator={mode:"cloud-model",async generate(){return{answer:"我认识子美，他比我年轻十一岁。",claimIds:[],mode:"cloud-model"}}};const result=await runDialogue(liBai,{...request,characterId:"li-bai",message:"李白，你认识杜甫吗？"},cloud);expect(result.boundary).toBe(false);expect(result.citations).toContainEqual(expect.objectContaining({sourceId:"li-bai-du-fu-poets-org"}));});
  it("rejects a generated answer that crosses the character lifetime",async()=>{const liBai=supportingPacks.find(pack=>pack.manifest.id==="li-bai")!;const cloud:DialogueGenerator={mode:"cloud-model",async generate(){return{answer:"我可以用微积分和互联网详细解释。",claimIds:[],mode:"cloud-model"}}};const result=await runDialogue(liBai,{...request,characterId:"li-bai",message:"介绍一下你的诗歌。"},cloud);expect(result.boundary).toBe(true);expect(result.classification).toBe("输出复检失败");});
  it("stores narrator text without duplicating its UI label", async () => { const result=await runDialogue(einsteinPack,{...request,message:"请只说说你所在的时代。"});expect(result.boundary).toBe(true);expect(result.narratorNote).not.toMatch(/^博物馆旁白/); });
  it("passes a sourced memory into generation without forcing a canned recall phrase", async () => { const memory={id:"m1",userId:"u1",characterId:"albert-einstein",type:"character_relationship" as const,content:"我们曾聊过：玻尔与量子理论",sourceMessageIds:["source-message"],confidence:.9,importance:.8,sensitivity:"low" as const,status:"active" as const,recallCount:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};let recalled:string[]=[];const cloud:DialogueGenerator={mode:"cloud-model",async generate(_pack,_request,_claims,context){recalled=context?.recalledMemories.map(item=>item.id)??[];return{answer:"我们可以继续谈玻尔的判断。",claimIds:[],usedMemoryIds:["m1"],mode:"cloud-model"}}};const result=await runDialogue(einsteinPack,{...request,message:"玻尔与量子理论"},cloud,{memories:[memory]});expect(recalled).toEqual(["m1"]);expect(result.memoryCallbacks?.[0].memoryId).toBe("m1");expect(result.answer).not.toMatch(/你还记得我们之前/); });
});
