"use client";
import { useEffect,useState } from "react";
export function AgentConsole(){
  const [tasks,setTasks]=useState<any[]>([]);const [topic,setTopic]=useState("量子理论发展");
  async function load(){const data=await fetch("/api/agent-tasks").then(response=>response.json());setTasks(data.tasks??[])}
  useEffect(()=>{void load()},[]);
  async function start(type:string,input:any={}){await fetch("/api/agent-tasks",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type,input})});await load()}
  async function action(id:string,name:string,body?:unknown){await fetch(`/api/agent-tasks/${id}/${name}`,{method:"POST",headers:{"content-type":"application/json"},body:body?JSON.stringify(body):undefined});await load()}
  return <main className="shell"><span className="eyebrow">SPECIALIST AGENTS</span><h1>博物馆任务中心</h1><p>人物对话保持低延迟；跨人物规划、知识加工、评测和媒体创作才进入可审计 Agent 工作流。</p><section className="agent-launch"><input value={topic} onChange={event=>setTopic(event.target.value)}/><button onClick={()=>void start("guide",{topic})}>生成学习路线</button><button onClick={()=>void start("evaluation",{characterId:"albert-einstein"})}>评测爱因斯坦包</button><button onClick={()=>void start("knowledge",{source:"studio"})}>规划知识加工</button><button onClick={()=>void start("media",{characterId:"albert-einstein"})}>创建人物合影</button></section><div className="memory-grid">{tasks.map(task=><section key={task.id}><small>{task.type} · {task.provider}/{task.model} · 尝试 {task.attempt}/3</small><h2>{task.status}</h2>{task.errorCode&&<p className="error">{task.errorCode}</p>}<ol>{task.plan.map((item:any)=><li key={item.id}>{item.name} — {item.status}{item.detail?`：${item.detail}`:""}</li>)}</ol>{task.status==="waiting_review"&&<button onClick={()=>void action(task.id,"confirm",task.errorCode==="CONSENT_REQUIRED"?{consentId:crypto.randomUUID()}:undefined)}>{task.errorCode==="CONSENT_REQUIRED"?"同意仅用于本次任务":"确认审核"}</button>}{task.status==="failed"&&task.attempt<3&&<button onClick={()=>void action(task.id,"retry")}>重试</button>}{!["completed","cancelled"].includes(task.status)&&<button className="danger" onClick={()=>void action(task.id,"cancel")}>取消任务</button>}{task.artifactIds.map((id:string)=><a key={id} href={`/api/artifacts/${id}`} target="_blank">查看产物</a>)}</section>)}</div></main>;
}
