import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Breadcrumbs, JsonLd } from "@/components/public/JsonLd";
import { absoluteSiteUrl, publicHall, publicHallIds } from "@/lib/public-museum";

export const dynamicParams = false;
export function generateStaticParams(){return publicHallIds().map((id)=>({id}));}

export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;const data=publicHall(id);if(!data)return{};const {pack}=data;const description=`${pack.hall.title}：${pack.hall.question}${pack.hall.guideText}`;const image=pack.assets[0];return{title:pack.hall.title,description,alternates:{canonical:`/halls/${id}`},openGraph:{title:pack.hall.title,description,url:`/halls/${id}`,images:image?[{url:image.path,alt:image.alt}]:undefined}};}

export default async function HallPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const data=publicHall(id);if(!data)notFound();const {pack,period,characters}=data;const object=pack.objects[0];const image=pack.assets[0];return <main className="public-page"><JsonLd data={{"@context":"https://schema.org","@type":"LearningResource",name:pack.hall.title,description:pack.hall.guideText,educationalUse:"museum learning",inLanguage:"zh-CN",url:absoluteSiteUrl(`/halls/${id}`)}}/><Breadcrumbs items={[{label:"首页",href:"/"},{label:"历史时期",href:"/periods"},{label:period.title,href:`/periods/${period.id}`},{label:pack.hall.title}]}/><header className="public-page-hero"><p className="public-eyebrow">{pack.hall.entrance.kicker}</p><h1>{pack.hall.title}</h1><p className="public-lead">{pack.hall.question}</p>{pack.hall.contentWarning&&<p className="notice"><b>{pack.hall.contentWarning.label}：</b>{pack.hall.contentWarning.description}</p>}</header><div className="public-content-grid"><article className="public-article">{image&&<img className="public-hall-image" src={image.path} alt={image.alt}/>}<section><p className="public-eyebrow">导览</p><h2>{pack.hall.guideTitle}</h2><p>{pack.hall.guideText}</p></section>{object&&<section><p className="public-eyebrow">主题物件 · {object.dateLabel}</p><h2>{object.name}</h2><p>{object.description}</p><div className="public-question"><h3>它为什么重要？</h3><p>{object.significance}</p></div><small>{object.representation === "evidence_based_reconstruction" ? "教育性证据重建，不作为原始史料图像。" : object.representation}</small></section>}<section><h2>谁与这个问题相连？</h2><div className="public-index-grid">{characters.map((character,index)=><a className="public-index-card" href={`/people/${character.id}`} key={character.id}><img src={character.portraitVariants.cartoon.assetPath} alt=""/><h3>{character.name}</h3><p>{pack.hall.characterRefs[index]?.relationshipLabel??character.summary}</p></a>)}</div></section><section><p className="public-eyebrow">离开展厅前</p><h2>{pack.hall.exit.reflectionQuestion}</h2><p>这个问题没有自动生成的标准答案。它用于把展厅中的人物、证据和选择重新联系起来。</p></section><section><h2>策展来源</h2><div className="public-source-list">{pack.sources.map(source=><article key={source.id}><b>{source.title}</b><p>{source.note}</p></article>)}</div></section></article><aside><div className="public-aside-card"><p className="public-eyebrow">所属时期</p><h2>{period.title}</h2><p>{period.years}<br/>{period.place}</p><div className="public-link-list"><a href={`/periods/${period.id}`}>查看完整时期馆</a>{period.halls.filter(hall=>hall.id!==id).map(hall=><a href={`/halls/${hall.id}`} key={hall.id}>{hall.title}</a>)}</div><div className="public-actions"><a className="public-button primary" href="/login?next=/museum">登录后进入沉浸展厅</a></div></div></aside></div></main>}
